# Generated by Django 2.1.5 on 2019-02-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='gambar',
            field=models.ImageField(upload_to='images'),
        ),
    ]
