# Generated by Django 2.1.7 on 2019-02-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='gambar',
            field=models.ImageField(upload_to='images'),
        ),
    ]
